### ISSUE TITLE
Where can I find dataset in da4_data?

### ISSUE THREAD

**Issue by yizhihenpidehou** [ssc-oscar/BIMAN_bot_detection#3]
I could not find the dataset mentioned in bot_datagen.ipynb in the first cell. Could you please offer me an access link?

**Comment by tapjdey** [comment]
@yizhihenpidehou Please use the dataset named "[snapshot_paper_a2c.gz](https://github.com/ssc-oscar/BIMAN_bot_detection/blob/master/data_snapshot/snapshot_paper_a2c.gz)" from the "data_snapshot" folder. 

The "da4_data" location was a temporary one so I would suggest using all datasets from the "data_snapshots" folder itself. Apologies for the confusion.

Please reopen the issue for any lingering concerns.
